language: c # defaults to ruby
addons:
  apt_packages:
  - zsh
  - ksh
install:
    - (cd /tmp && wget https://raw.github.com/tlevine/urchin/master/urchin && chmod +x urchin)
  - '[ -z "$WITHOUT_CURL" ] || sudo apt-get remove curl -y'
script:
  - /tmp/urchin -f -s "$TEST_SHELL" "test/$TEST_SUITE"
env:
  - TEST_SHELL=bash TEST_SUITE=install_script
  - TEST_SHELL=sh TEST_SUITE=fast
  - TEST_SHELL=dash TEST_SUITE=fast
  - TEST_SHELL=bash TEST_SUITE=fast
  - TEST_SHELL=zsh TEST_SUITE=fast
#  - TEST_SHELL=ksh TEST_SUITE=fast
  - TEST_SHELL=sh TEST_SUITE=slow
  - TEST_SHELL=dash TEST_SUITE=slow
  - TEST_SHELL=bash TEST_SUITE=slow
  - TEST_SHELL=zsh TEST_SUITE=slow
#  - TEST_SHELL=ksh TEST_SUITE=slow
  - TEST_SHELL=sh TEST_SUITE=sourcing
  - TEST_SHELL=dash TEST_SUITE=sourcing
  - TEST_SHELL=bash TEST_SUITE=sourcing
  - TEST_SHELL=zsh TEST_SUITE=sourcing
#  - TEST_SHELL=ksh TEST_SUITE=sourcing
  - TEST_SHELL=sh TEST_SUITE=installation
  - TEST_SHELL=sh TEST_SUITE=installation WITHOUT_CURL=1
  - TEST_SHELL=dash TEST_SUITE=installation
  - TEST_SHELL=dash TEST_SUITE=installation WITHOUT_CURL=1
  - TEST_SHELL=bash TEST_SUITE=installation
  - TEST_SHELL=bash TEST_SUITE=installation WITHOUT_CURL=1
  - TEST_SHELL=zsh TEST_SUITE=installation
  - TEST_SHELL=zsh TEST_SUITE=installation WITHOUT_CURL=1
#  - TEST_SHELL=ksh TEST_SUITE=installation
#  - TEST_SHELL=ksh TEST_SUITE=installation WITHOUT_CURL=1
